[package]
name = "filessh"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.51", features = ["derive"] }
color-eyre = "0.6.5"
crossbeam = "0.8.4"
derive-getters = "0.5.0"
directories = "6.0.0"
futures = "0.3.31"
rat-focus = "1.3.0"
rat-ftable = "1.2.0"
rat-salsa = { version = "2.2.0", features = ["async"] }
rat-theme3 = "2.3.0"
rat-widget = "2.1.0"
ratatui = "0.29.0"
russh = "0.54.6"
russh-sftp = "2.1.1"
shell-escape = "0.1.5"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
