debug = false
silent = false

[theme]
name = "Dark"
type_ = "Dark"

[theme.palette]
name = "Imperial"
text_light = "#DEDFE3"
text_bright = "#F6F6F3"
text_dark = "#2A2B37"
text_black = "#0F1014"
white = ["#DEDFE3", "#E6E6E8", "#EEEFEE", "#F6F6F3", "#363738", "#383839", "#3A3B3A", "#3C3C3C"]
black = ["#0F1014", "#18191F", "#21222C", "#2A2B37", "#030304", "#050607", "#08080A", "#0A0A0D"]
gray = ["#3B3D4E", "#4C4E64", "#5D617B", "#6E7291", "#0E0F13", "#121318", "#16171E", "#1B1C23"]
red = ["#480F0F", "#761919", "#A42323", "#D22D2D", "#110303", "#1D0606", "#280808", "#330B0B"]
orange = ["#482C0F", "#764818", "#A66522", "#D4812B", "#110A03", "#1D1105", "#291808", "#341F0A"]
yellow = ["#756600", "#A38E00", "#D1B600", "#FFDE00", "#1C1900", "#282300", "#332C00", "#3F3600"]
limegreen = ["#2C4611", "#48731B", "#64A127", "#80CE31", "#0A1104", "#111C06", "#182709", "#1F320C"]
green = ["#186218", "#208520", "#2AAA2A", "#32CD32", "#051805", "#072007", "#0A2A0A", "#0C320C"]
bluegreen = ["#206A52", "#29886A", "#32A682", "#3BC49A", "#071A14", "#0A211A", "#0C2920", "#0E3026"]
cyan = ["#0F2C48", "#186476", "#229CA6", "#2BD4D4", "#030A11", "#05181D", "#082629", "#0A3434"]
blue = ["#162B41", "#1D4772", "#2465A3", "#2B81D4", "#050A10", "#07111C", "#081828", "#0A1F34"]
deepblue = ["#202083", "#26269B", "#2C2CB5", "#3232CD", "#070720", "#090926", "#0A0A2C", "#0C0C32"]
purple = ["#4D008B", "#6200B1", "#7700D7", "#8C00FD", "#130022", "#18002B", "#1D0035", "#22003E"]
magenta = ["#401640", "#692469", "#943494", "#BD42BD", "#0F050F", "#190819", "#240C24", "#2E102E"]
redpink = ["#47101D", "#701E31", "#9A2E47", "#C33C5B", "#110307", "#1B070C", "#260B11", "#300E16"]
primary = ["#300057", "#4E008E", "#6E00C6", "#8C00FD", "#0B0015", "#130023", "#1B0030", "#22003E"]
secondary = ["#574B00", "#8F7C00", "#C7AD00", "#FFDE00", "#151200", "#231E00", "#312A00", "#3F3600"]
